[build]
  functions = "functions"

[dev]
  command = "npm run start"
  port = 3999
  targetPort = 3000
  publish = "."
  autoLaunch = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/config"
  to = "/.netlify/functions/config"
  status = 200
  force = true



